'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { useRouter } from "next/navigation";
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { WagmiProvider } from 'wagmi';
import { RainbowKitProvider, type Locale } from '@rainbow-me/rainbowkit';

import './globals.css';
import '@rainbow-me/rainbowkit/styles.css';

import { config } from '../walletConnet';

// Initialize the Inter font
const inter = Inter({ subsets: ["latin"] });

// Initialize QueryClient for react-query
const queryClient = new QueryClient();

// Set up metadata for your app
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Use Next.js navigation hook for routing
  const router = useRouter();
  const locale = router.locale as Locale;

  return (
    <html lang="en">
      <body className={inter.className}>
        <WagmiProvider config={config}>
          <QueryClientProvider client={queryClient}>
            <RainbowKitProvider locale={locale} >
              {children}
            </RainbowKitProvider>
          </QueryClientProvider>
        </WagmiProvider>
      </body>
    </html>
  );
}
