[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
linea-goerli = "https://linea-sepolia.g.alchemy.com/v2/${API_KEY}"

[etherscan]
arbitrum = { key = "${ARBISCAN_API}", chain=421614 }